version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 710876723829.dkr.ecr.eu-central-1.amazonaws.com
      - echo Logging successful.

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t ak-ecs-demo .
      - docker tag ak-ecs-demo:latest 710876723829.dkr.ecr.eu-central-1.amazonaws.com/ecs-demo:latest

  post_build:
    commands:
      - echo Pushing the Docker image to Amazon ECR...
      - docker push 710876723829.dkr.ecr.eu-central-1.amazonaws.com/ecs-demo:latest
      - echo Build and push completed successfully.
      - printf '[{\"name\":\"nginx\",\"imageUri\":\"710876723829.dkr.ecr.eu-central-1.amazonaws.com/ecs-demo:latest\"}]' > imagedefinitions.json
      - echo Build and push completed successfully.

artifacts:
  files:
    - imagedefinitions.json